"""Add wallet and contract fields to User

Revision ID: d2cc0e28887f
Revises: 
Create Date: 2025-07-10 02:43:32.968665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cc0e28887f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('private_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('wallet_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('campaign_contract_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('factory_contract_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'factory_contract_address')
    op.drop_column('users', 'campaign_contract_address')
    op.drop_column('users', 'wallet_address')
    op.drop_column('users', 'private_key')
    # ### end Alembic commands ###
